---
- name: copy 
  hosts: test-servers
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "copy file"
      copy: src=/home/edureka/Documents/index.html dest=/var/www/html/index.html
    - name: "copy file"
      copy: src=/home/edureka/Documents/process.php dest=/var/www/html/process.php
    - name: "copy file"
      copy: src=/home/edureka/Documents/results.php dest=/var/www/html/result.php
          